# Generated by Django 4.1.7 on 2023-03-03 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolYouthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_belakang', models.CharField(blank=True, max_length=255, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=255, unique=True)),
                ('nama_cool', models.CharField(blank=True, max_length=255, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('status_pekerjaan', models.CharField(blank=True, max_length=255, null=True)),
                ('domisili', models.CharField(blank=True, max_length=255, null=True)),
                ('pengerja_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
